### ISSUE TITLE
Merging the firmware into the mainline QMK repo

### ISSUE THREAD

**Issue by drlkf** [dlip/harite#4]
Hi!
Many QMK tools are built to use the mainline repository so it's quite inconvenient to use a separate repository. Are there any plans to merge your `qmk_firmware` fork into the mainline? I can help curate and squash the commits if necessary, let me know.
Cheers!

**Comment by dlip** [comment]
@drlkf i don't mind making a pr to add it to the mainline, I had a bit of a negative experience in the past when i was trying to add some of my userspace code for taipo and ended up giving up and just using my own fork. I would probably only submit the default layout with the testing keys, since they would probably reject my layout with the huge chords file. Maybe I would add another layout later when I have created a harite optimized layout.

**Comment by drlkf** [comment]
>I had a bit of a negative experience in the past when i was trying to add some of my userspace code for taipo and ended up giving up

That's what I was expecting :') that's ok, I figured out a setup to switch between the two, I'll close this issue. Thanks!
